2022-Sept/23 Sept 2022/Mayur_Borgude.cpp

Mayur Borgude

---

2022-Sept/24 Sept 2022/rucha_kale.py

I have Created the pattern as per the given question.

Created by Rucha Kale

---

2022-Sept/24 Sept 2022/Aditya_salve.cpp

i have done whatever you said if anything is wrong let me know.Thank you

Aditya_salve.cpp

---

2022-Sept/25 Sept 2022/Star_Pattern.java

taken number from user and print star pattern

Star_Partten code added

---

2022-Sept/24 Sept 2022/mohee_athani.py

I have created the pattern as per question

Created by mohee athani

---

vaishnavi_gosavi.java

I have created program for checking Palindrome.

Created by  vaishnavi_gosavi.java

---

2022-Oct/01 Oct 2022/palindrome.py

This is the python program to check whether the string is palindrome or not...
Code has comments so that anyone going through could easily get it.
Simple and effective python code

Prathamesh_Patil.py

---

2022-Oct/03 Oct 2022/ryan_souza.hs

@Yashkapure06 Please review this PR (Pull Request) and label this PR as "hacktoberfest-accept".

Solution 03/10 - create ryan_souza.hs

---

2022-Oct/04 Oct 2022/joel_sathiyendra.py

I have added the solution to Anagram pattern problem in python. Please review it and let me know.

Anagram created by Joel

---

2022-Oct/05 Oct 2022/Isuru_Gunarathne.py

I added a solution for MAX length of a word from a string (Oct 5). Please review and let me know what you think.

Add solution for OCT 5 by Isuru Gunarathne

---

2022-Sept/29 Sept 2022/Hariraj_Arunachalam.go

Adding solution using Golang for below

Pattern Created by Hariraj using Golang for 29Sept2022

---

2022-Oct/05 Oct 2022/Johnnie_Emmanuel.js
2022-Oct/06 Oct 2022/Johnnie_Emmanuel.js

The solution for the problem for 5th and 6th october in javascript

added javascript solutions for the programming problem

---

2022-Oct/05 Oct 2022/vaibhav_singh.js

feat: added javascript code for 5-10-22

---

2022-Oct/04 Oct 2022/Utkarsh_Prajapati.py
2022-Oct/05 Oct 2022/Utkarsh_Prajapati.py
2022-Oct/06 Oct 2022/Utkarsh_Prajapati.py

Added the solution for today's question

[PYTHON] Added the solution

---

2022-Oct/07 Oct 2022/Johnnie_Emmanuel.js

javascript solution for the palindrome problem

added the javascript solution for the palindrome problem for 7th oct

---

Rahul-Jain-1.cpp

I have done today problem(7th October 2022)  in c++ language.
pls merge this pull request.

Create by Rahul-Jain-1 in cpp

---

2022-Oct/07 Oct 2022/Asliutkarsh.java

Added Solution of Longest Palindrome in Java
--> Reversed the string
--> Checking Palindrome
--> Splitting sentence into words
--> Check if it is palindrome or not, if yes then check if it is longest

Added Solution of Longest Palindrome in Java

---

2022-Sept/28 Sept 2022/Hariraj_Arunachalam.go

-  Double side Pattern Created by Hariraj using Go for 28Sept2022

Double side Pattern Created by Hariraj using Go for 28Sept2022

---

2022-Sept/27 Sept 2022/Hariraj_Arunachalam.go

- L-shaped Pattern Created by Hariraj using Go for 27Sept2022

Pattern Created by Hariraj using Go for 27Sept2022

---

2022-Sept/26 Sept 2022/Hariraj_Arunachalam.go

- L-shaped number pattern created by Hariraj using Go for 26Sept2022

Pattern Created by Hariraj using Go for 26Sept2022

---

2022-Sept/24 Sept 2022/Hariraj_Arunachalam.go

- Using Go, created this pattern

Number pattern created by Hariraj for 24Sept2022

---

2022-Oct/08 Oct 2022/aditya_sai.java

Pattern Created by Aditya Sai

---

2022-Oct/08 Oct 2022/Vaishnavi_Kapadi_permutation.cpp

I have created the code for Permutation

Created by Vaishnavi_kapadi

---

2022-Oct/07 Oct 2022/aditya_sai.py

Hacktoberfest submission
@Yashkapure06

Created by Aditya Sai

---

2022-Oct/08 Oct 2022/ratijindal.java

Using Backtracking and Swap Function

Added Solution of 8 October

---

2022-Oct/09 Oct 2022/Aryan_V_S.cpp

All combinations generated iteratively using subsets.
Output:
```
$ g++ Aryan_V_S.cpp -o main -Wall -Wextra -pedantic -std=c++17
$ echo "ABC" | ./main
"ABC BC AC C AB B A  "
```

add solution for 09-Oct-2022

---

2022-Oct/09 Oct 2022/Kunal_Nandre.java

Kunal_Nandre.java

---

2022-Oct/11 Oct 2022/Aryan_V_S.cpp

A line is read as input and split based on spaces. Each word is then checked if palindrome or not.
Some assumptions made are:
- Palindromes are case-insensitive
- Punctuation is not accounted for ("racecar." is not considered a palindrome)
Output:
```
$ g++ Aryan_V_S.cpp -o main -Wall -Wextra -pedantic -std=c++17
$ echo "I use Racecar, isn't it cool. aba baab AAbBAa" | ./main
4
```
The palindromes are "I", "aba", "baab" and "AAbBAa" here (note that "Racecar" isn't accounted for due to punctuation).

add solution for 11-Oct-2022

---

2022-Oct/09 Oct 2022/ratnesh-maurya.cpp

SOLUTION IN CPP

---

2022-Oct/12 Oct 2022/muskan_verma.py

Accept two list from the user and find common element from the both list code in python

ProCode created by MuskanVerma

---

2022-Oct/01 Oct 2022/Hariraj_Arunachalam.go

- Add Palindrome using string reversal

Palindrome in Golang by Hariraj

---

2022-Oct/08 Oct 2022/AyushYadav.cpp

Addes Cpp Source Code

---

2022-Oct/13 Oct 2022/README.md

rectify roate to rotate

---

2022-Oct/13 Oct 2022/Tusshar_Paul.cpp

13/10/2022
Accept array from user and rotate it from left by one place

solution to Problem of 13/10/2022.cpp

---

2022-Oct/16 Oct 2022/TanyaAhuja16oct.cpp

I have added cpp solution for 16oct problem, kindly review it and merge my changes under hacktoberfest accepted label.
Thank you!!

adding solution for 16oct.

---

2022-Oct/16 Oct 2022/venkat_swaraj.py

Python code for adding two 2D array.

add 2 2D array by Venkat Swaraj

---

2022-Oct/15 Oct 2022/venkat_swaraj.py

Added python code for rotating an array by D times using list slicing.

Rotating array by D times Created by Venkat Swaraj

---

2022-Oct/16 Oct 2022/Tusshar_Paul.cpp

Sum of two 2D ARRAY in Cpp Language

Solution to problem of 16/10/2022.cpp

---

2022-Oct/04 Oct 2022/Hariraj_Arunachalam.go

- Validate the strings are anagrams

Validate anagram using Golang by Hariraj

---

2022-Oct/15 Oct 2022/Nikit.go

Added golang code for 15th october problem statement.

Added golang code for 15th october problem statement.

---

2022-Oct/15 Oct 2022/Michael_Giardina.py

Please let me know if there are any issues or concerns.

October 15th Created by Michael Giardina

---

2022-Oct/02 Oct 2022/Hariraj_Arunachalam.go

- Calculate capital letters in go

Calculate capital letters in Golang By Hariraj

---

2022-Oct/16 Oct 2022/Chathura_Gunasekara.py

A Solution for the 16/10/2022 question using python 3

Creating Chathura_Gunasekara.py

---

2022-Oct/18 Oct 2022/Moses_Rukshan.py.py

I have added the solution to find the transpose of the matrix. please review and let me know.

Transpose of the matrix created by Rukshan

---

2022-Oct/18 Oct 2022/omprakash.java

Added java code for 18oct problem.

Added java code for 18oct problem.

---

2022-Oct/18 Oct 2022/TransposeMatrix.java

-In this JAVA solution, ArrayList<> is being used.

Added Transpose of the Matrix problem

---

2022-Oct/15 Oct 2022/Tusshar_Paul.cpp

Accept array from user and rotate it from left by d place

Solution to Problem of 15/10/2022 added.cpp

---

2022-Oct/15 Oct 2022/Sahil_kumar_singh.cpp

First I am taking the array size as input. Then taking the input in array and 'd' as well. Then rotate the array by d from the left.

solution of 15 oct 2022

---

2022-Oct/05 Oct 2022/Hariraj_Arunachalam.go

- Find largest word in a sentence using recursion by Hariraj

Find largest word in a sentence using recursion

---

2022-Oct/18 Oct 2022/Nandhika.java

This file contains the solution for the proposed problem in java language.

Nandhika.java

---

2022-Oct/21 Oct 2022/Mayank_Sahu.cpp

solved 21 Oct problem statement in CPP

21 oct Created By Mayank Sahu

---

2022-Oct/21 Oct 2022/Kratik_Jain.cpp

Solved 21oct 2022 problem statement using c++.
Myself Kratik.
I am adding solution to 21 oct 2022 problem statement in form of cpp file as i solved it in C++ language.
Kindly consider my solution and merge it and help me with hactoberfest pr.
#hactoberfest2022.
Thank You.

"21 oct 2022 Created by Kratik Jain in c++"

---

2022-Oct/21 Oct 2022/dev_zohaib.py

I have added python solution 21 October 22 problem.

Multiplication Created by devzohaib

---

2022-Oct/16 Oct 2022/Nikit.go

Added golang code for 16th october problem statement.

Added golang code for 16th october problem statement.

---

2022-Oct/18 Oct 2022/Himanshu_Koshti.cpp
2022-Oct/21 Oct 2022/himanshu_koshti.c

program to multiply two matrix of size n
Himanshu Koshti

program to multiply two matrix of size n

---

2022-Oct/06 Oct 2022/Hariraj_Arunachalam.go

- Reverse the words in a sentence in golang

feat: Reverse the words in a sentence

---

2022-Oct/16 Oct 2022/rojarani_akkisetty.cs

C# Program to print Addition of two n x n matrices

Matrix Addition Created by Rojarani

---

2022-Oct/04 Oct 2022/dev_zohaib.py

I have added isAnagram of two string in 04 Oct 2022.

isAnagram Created by devzohaib
